SMS/SMS/SMS/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('adminapp.urls')),
    path('facultyapp/', include('facultyapp.urls')),
    path('studentapp/', include('studentapp.urls')),
]

SMS/SMS/facultyapp/urls.py
app_name='facultyapp'
from django.urls import path
from . import views

urlpatterns = [
    path('', views.FacultyHomePage, name='FacultyHomePage'),
path('addblogpagecall/',views.addblogpagecall,name='addblogpagecall'),
path('add_blog/',views.add_blog,name='add_blog'),
path('<int:pk>/delete/',views.delete_blog,name='delete_blog'),
path('add_course/',views.add_course,name='add_course'),
path('post_marks/',views.post_marks,name='post_marks'),
path('view_student_list/',views.view_student_list,name='view_student_list'),

]

SMS/SMS/studentapp/urls.py
from django.urls import path,include
from . import views
app_name='studentapp'
# to communicate between the apps we have to mention the app name
urlpatterns = [
    path('', views.StudentHomePage, name='StudentHomePage'),
    path('view_marks/', views.view_marks, name='view_marks'),

]

SMS/SMS/templates/Navbar/FacultyNavBar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student Management System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href=" {% url 'facultyapp:FacultyHomePage' %} ">SMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyapp:addblogpagecall' %}">Add Blogs</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyapp:add_course' %}">Add Course</a>
        </li>
                    <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyapp:view_student_list' %}">View Student List</a>
        </li>
                  <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyapp:post_marks' %}">PostMarks</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
      </ul>
    </div>
  <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'registerpagecall' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'loginpagecall' %}">Login</a>
        </li>
        {% endif %}
 </li>
      </ul>
  </div>
</nav>
{% block body %}

{% endblock %}
</body>
</html>

SMS/SMS/templates/Navbar/ProjectNavBar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student Management System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href=" {% url 'projecthomepage' %} ">SMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            PFSD Concepts
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="{% url 'printpagecall' %}">Printer</a></li>
              <li><a class="dropdown-item" href="{% url 'randompagecall' %}">OTP Generator</a></li>
              <li><a class="dropdown-item" href="{% url 'exceptionpagecall' %}">Exception</a></li>
            <li><a class="dropdown-item" href="{% url 'calculatorpagecall' %}">Calculator</a></li>
              <li><a class="dropdown-item" href="{% url 'timepagecall' %}">TimeZone</a></li>
            <li><a class="dropdown-item" href="{% url 'add_task' %}">To Do App</a></li>
              <li><a class="dropdown-item" href="{% url 'graphpagelogic' %}">Graph Generator</a></li>
               <li><a class="dropdown-item" href="{% url 'add_feedback' %}">Feedback Form</a></li>
              <li><a class="dropdown-item" href="{% url 'add_contact' %}">Contact Manager</a></li>
          </ul>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'add_student' %}">Add Students</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=#>View Students List</a>
        </li>
      </ul>
    </div>
  <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'registerpagelogic' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'loginpagecall' %}">Login</a>
        </li>
        {% endif %}
 </li>
      </ul>
  </div>
</nav>
{% block body %}

{% endblock %}
</body>
</html>

SMS/SMS/templates/Navbar/StudentNavBar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student Management System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href=" {% url 'studentapp:StudentHomePage' %} ">SMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'studentapp:view_marks' %}">Home</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'studentapp:view_marks' %}">View Marks</a>

        </li>

      </ul>
    </div>
  <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'registerpagecall' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'loginpagecall' %}">Login</a>
        </li>
        {% endif %}
 </li>
      </ul>
  </div>
</nav>
{% block body %}

{% endblock %}
</body>
</html>