SMS/SMS/SMS/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('adminapp.urls')),
    path('facultyapp/', include('facultyapp.urls')),
    path('studentapp/', include('studentapp.urls')),
]

SMS/SMS/facultyapp/urls.py
app_name='facultyapp'
from django.urls import path
from . import views

urlpatterns = [
    path('', views.FacultyHomePage, name='FacultyHomePage'),
path('addblogpagecall/',views.addblogpagecall,name='addblogpagecall'),
path('add_blog/',views.add_blog,name='add_blog'),
path('<int:pk>/delete/',views.delete_blog,name='delete_blog'),
path('add_course/',views.add_course,name='add_course'),
path('post_marks/',views.post_marks,name='post_marks'),
path('view_student_list/',views.view_student_list,name='view_student_list'),

]

SMS/SMS/facultyapp/models.py
from django.db import models
from django.db import models
from adminapp .models import StudentList
from django.contrib.auth.models import User
# Create your models here.Tp store any data in database we should write in models.py. This class is stored as a table in the database
#Make migrations: used to convert class to table in the database
class Blog(models.Model):
    title= models.CharField(max_length=200)
    content=models.CharField(max_length=300)

    def str(self):
        return self.title

class AddCourse(models.Model):
    COURSE_CHOICES=[
        ('AOOP','Advanced Object Oriented Programming'),
        ('PFSD', 'Python Full Stack Development'),
        ('DBMS','DataBase Management System'),
        ('LAA', 'Linux Automation and Administration'),
    ]
    SECTION_CHOICES=[
        ('S11','Section11'),
        ('S12', 'Section12'),
        ('S13', 'Section13'),
        ('S14', 'Section14'),
        ('S15', 'Section15'),
    ]
    student=models.ForeignKey(StudentList,on_delete=models.CASCADE)
    course=models.CharField(max_length=50,choices=COURSE_CHOICES)
    section=models.CharField(max_length=50,choices=SECTION_CHOICES)
    def __str__(self):
        return f'{self.student.Register_Number} - {self.course} ({self.section})'

class Marks(models.Model):
    COURSE_CHOICES = [
        ('AOOP', 'Advanced Object Oriented Programming'),
        ('PFSD', 'Python Full Stack Development'),
        ('DBMS', 'DataBase Management System'),
        ('LAA', 'Linux Automation and Administration'),
    ]
    student = models.ForeignKey(StudentList, on_delete=models.CASCADE)
    course = models.CharField(max_length=50, choices=COURSE_CHOICES)
    marks = models.IntegerField()

    def __str__(self):
        return f'{self.student.name} - {self.course} )'

SMS/SMS/facultyapp/forms.py
import pytz
from django import forms
from .models import Blog, Marks, AddCourse


# from .models import Marks
#It will resuce the lines of code in HTML file and views.py.When the no.of parametres in more we can use forms.py This file is not mandatory
# is_valid() - Checks the form whether all the fields are filled or not in the form
# form.save() - saves the information in the database
class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title','content']

class AddCourseForm(forms.ModelForm):
    class Meta:
        model=AddCourse
        fields=['student','course','section']

class MarksForm(forms.ModelForm):
    class Meta:
        model=Marks
        fields=['student','course','marks']

SMS/SMS/facultyapp/views.py
from django.core.mail import send_mail
from django.shortcuts import render, redirect, get_object_or_404
from .models import Blog
from .forms import BlogForm, MarksForm


def FacultyHomePage(request):
    return render(request, "facultyapp/FacultyHomePage.html")
def addblogpagecall(request):
    return render(request,'facultyapp/add_blog.html')
def add_blog(request):
    if request.method=='POST':
        form = BlogForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('facultyapp:add_blog')
    else:
        form=BlogForm()
    blogs = Blog.objects.all()
    return render(request,'facultyapp/add_blog.html',{'form':form,'blogs':blogs})

def delete_blog(request,pk):
    blog=get_object_or_404(Blog,pk=pk)
    blog.delete()
    return redirect('facultyapp:add_blog')


from .forms import AddCourseForm
def add_course(request):
    if request.method == 'POST':
        form = AddCourseForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('facultyapp:FacultyHomePage')
    else:
        form = AddCourseForm()
    return render(request, 'facultyapp/addCourse.html', {'form': form})


from .models import AddCourse
from adminapp.models import StudentList

def view_student_list(request):
    course = request.GET.get('course')
    section = request.GET.get('section')
    student_courses = AddCourse.objects.all()
    if course:
        student_courses = student_courses.filter(course=course)
    if section:
        student_courses = student_courses.filter(section=section)
    students = StudentList.objects.filter(id__in=student_courses.values('student_id'))
    course_choices = AddCourse.COURSE_CHOICES
    section_choices = AddCourse.SECTION_CHOICES
    context = {
        'students': students,
        'course_choices': course_choices,
        'section_choices': section_choices,
        'selected_course': course,
        'selected_section': section,
    }
    return render(request, 'facultyapp/view_student_list.html', context)

def post_marks(request):
    if request.method == "POST":
        form = MarksForm(request.POST)
        if form.is_valid():
            marks_instance = form.save(commit=False)
            marks_instance.save()
            # Retrieve the User email based on the student in the form
            student = marks_instance.student
            student_user = student.user
            user_email = student_user.email
            subject = 'Marks Entered'
            message = f'Hello, {student_user.first_name} {student_user.last_name}  marks for {marks_instance.course} have been entered. Marks: {marks_instance.marks}'
            from_email = 'revathiyadlapalli6@gmail.com'
            recipient_list = [user_email]
            send_mail(subject, message, from_email, recipient_list)
            return render(request, 'facultyapp/post_markssuccess.html')
    else:
        form = MarksForm()
    return render(request, 'facultyapp/post_marks.html', {'form': form})

SMS/SMS/templates/facultyapp/FacultyHomePage.html
{% extends 'Navbar/FacultyNavBar.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student Management System - Faculty</title>
</head>
<body>
{% block body %}
<h1 align="center">Welcome To Y23 - PFSD   Faculty</h1>
<div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'images/i1.jpg' %}" class="d-block w-100" alt="image1" height="600px" width="100%">
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/i2.jpg' %}" class="d-block w-100" alt="image2" height="600px" width="100%">
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/i3.jpg' %}" class="d-block w-100" alt="image3" height="600px" width="100%">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
{% endblock %}
</body>
</html>

SMS/SMS/templates/facultyapp/ViewBlog.html
{% extends 'Navbar/FacultyNavBar.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Printer</title>
</head>
<body>
{% block body %}

<div class="container text-center">
  <div class="row">
    <div class="col">
      First in DOM, no order applied
        <br><br>
            <h2>Blog List</h2>
<table>
    <tr>
        <th>Title</th>
        <th>Content</th>
    </tr>
    {% for blog in blogs %}
    <tr>
        <td>{{ blog.Title }}</td>
        <td>{{ blog.Content }}</td>
    </tr>
    {% endfor %}
</table>
    </div>
      <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
      <br><br><br><br><br><br><br>
       <div class="col-auto d-flex align-items-center">
      <div style="border-left: 2px solid black; height: 100%;"></div>
    </div>
    <div class="col">
        <br><br>


    </div>

  </div>
</div>
{% endblock %}
</body>
</html>

SMS/SMS/templates/facultyapp/addCourse.html
{% extends 'Navbar/FacultyNavBar.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Course</title>
    <!-- Add Bootstrap for styling (optional) -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% block body %}
    <div class="container mt-5">
        <h2>Add Course for Student</h2>
        <form method="post" action="{% url 'facultyapp:add_course' %}">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_student" class="form-label">Select Student</label>
                {{ form.student }}
            </div>
            <div class="mb-3">
                <label for="id_course" class="form-label">Select Course</label>
                {{ form.course }}
            </div>
            <div class="mb-3">
                <label for="id_section" class="form-label">Select Section</label>
                {{ form.section }}
            </div>
            <button type="submit" class="btn btn-primary">Add Course</button>
        </form>
    </div>

    <!-- Add Bootstrap JS for any JavaScript functionality (optional) -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>
{% endblock %}
</body>
</html>

SMS/SMS/templates/facultyapp/add_blog.html
{% extends 'Navbar/FacultyNavBar.html' %}
{% load static %}
<head>
    <title>To-Do List</title>
</head>
<body>
{% block body %}
<div class="container text-center">
  <div class="row">
    <div class="col">
      First in DOM, no order applied
        <br><br>
            <h1>Add Blog</h1>
            <form method="post" action="{% url 'facultyapp:add_blog' %}">{% csrf_token %}
            {{ form.as_p }}
            <br><br>
            <div class="d-grid gap-2 col-6 mx-auto">
            <button class="btn btn-primary" type="submit">Submit</button>
            </div>
        </form>
    </div>
      <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
      <br><br><br><br><br><br><br><br><br><br><br>
       <div class="col-auto d-flex align-items-center">
      <div style="border-left: 2px solid black; height: 100%;"></div>
    </div>
    <div class="col">
        <br><br>
        <strong> Output will be displayed Here</strong>
              <h2>Blogs</h2>
    <ul>
        {% for blog in blogs %}
            <li>
                {{ blog.title }}
                <a href="{% url 'facultyapp:delete_blog' blog.pk %}">Delete</a>
            </li>
        {% endfor %}
    </ul>
    </div>

  </div>
</div>
{% endblock %}
</body>
</html>

SMS/SMS/templates/facultyapp/markAttendance.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

SMS/SMS/templates/facultyapp/post_marks.html
{% extends 'Navbar/FacultyNavBar.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Printer</title>
</head>
<body>
{% block body %}

<div class="container text-center">
  <div class="row">
    <div class="col">
      First in DOM, no order applied
        <br><br>
            <form method="POST">
        {% csrf_token %}
        <table class="table table-bordered">
          {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary">Post Marks</button>
      </form>

    </div>
      <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
      <br><br><br><br><br><br><br><br><br>
       <div class="col-auto d-flex align-items-center">
      <div style="border-left: 2px solid black; height: 100%;"></div>
    </div>
    <div class="col">
        <br><br>


    </div>

  </div>
</div>
{% endblock %}
</body>
</html>

SMS/SMS/templates/facultyapp/post_markssuccess.html
{% extends 'Navbar/FacultyNavBar.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Successsfully Posted Marks</h1>
<a href="{% url 'facultyapp:FacultyHomePage' %}">Return to home page</a>
</body>
</html>

SMS/SMS/templates/facultyapp/select_date_and_hours.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

SMS/SMS/templates/facultyapp/view_student_list.html
{% extends 'Bavbar/FacultyNavBar.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>View Student List</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% block body %}
    <div class="container mt-5">
        <h2>View Student List</h2>

        <form method="get" class="mb-4">
            <div class="row">
                <div class="col-md-4">
                    <label for="course" class="form-label">Select Course</label>
                    <select name="course" id="course" class="form-control">
                        <option value="">All Courses</option>
                        {% for value, label in course_choices %}
                            <option value="{{ value }}" {% if selected_course == value %}selected{% endif %}>{{ label }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-md-4">
                    <label for="section" class="form-label">Select Section</label>
                    <select name="section" id="section" class="form-control">
                        <option value="">All Sections</option>
                        {% for value, label in section_choices %}
                            <option value="{{ value }}" {% if selected_section == value %}selected{% endif %}>{{ label }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-md-4 mt-4">
                    <button type="submit" class="btn btn-primary mt-2">Filter</button>
                </div>
            </div>
        </form>

        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Register Number</th>
                    <th>Name</th>
                    <th>Course</th>
                    <th>Section</th>
                </tr>
            </thead>
            <tbody>
                {% if students %}
                    {% for student in students %}
                        <tr>
                            <td>{{ student.Register_Number }}</td>
                            <td>{{ student.Name }}</td>
                            <td>{{ student.addcourse_set.first.course }}</td>
                            <td>{{ student.addcourse_set.first.section }}</td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td colspan="4" class="text-center">No students found.</td>
                    </tr>
                {% endif %}
            </tbody>
        </table>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>
{% endblock %}
</body>
</html>